###############################################################
# Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

country-risk-frontend:

  springProfiles:
    - int

  appName: country-risk-frontend
  environment: int

  ingress:
    host: catenax-vas-int.demo.catena-x.net
    enabled: true

  certificate:
    host: "country-risk-dashboard.int.demo.catena-x.net"

  configmap:
    # Specifies whether a configmap should be created or not
    data:
      REACT_APP_AUTH_URL: 'https://centralidp.int.demo.catena-x.net/auth'
      REACT_APP_COUNTRY_RISK_API: 'https://vas-country-risk-backend.int.demo.catena-x.net'
      REACT_APP_PORTAL_FRONTEND: 'https://portal.int.demo.catena-x.net'
      REACT_APP_PORTAL_BACKEND: 'https://portal-backend.int.demo.catena-x.net'

country-risk-backend:

  springProfiles:
    - int

  appName: vas-country-risk-backend
  environment: int


  ingress:
    host: catenax-vas-int.demo.catena-x.net
    enabled: true

  certificate:
    host: "vas-country-risk-backend.int.demo.catena-x.net"

  configmap:
    # Specifies whether a configmap should be created
    data:
      spring_profiles_active: int
      APPLICATION_HOST: http://localhost:8080/api/dashboard
      SECURITY_ENABLED: 'true'
      # -- Endpoints for BPDM output gate
      application_partnersPoolUrl_bpdmAddressUrl: https://business-partners.int.demo.catena-x.net/companies/test-company/api/catena/output/addresses/search?
      application_partnersPoolUrl_bpdmSiteUrl: https://business-partners.int.demo.catena-x.net/companies/test-company/api/catena/output/sites/search?
      application_partnersPoolUrl_bpdmLegalUrl: https://business-partners.int.demo.catena-x.net/companies/test-company/api/catena/output/legal-entities/search?
      vas_auth_url: https://centralidp.int.demo.catena-x.net
      REACT_APP_COUNTRY_RISK_CLIENT: 'app9'

  applicationSecret:
    clientSecret: <path:value-added-service/data/country-risk/int/keycloak#country-risk-client-secret>
    clientId: <path:value-added-service/data/country-risk/int/keycloak#country-risk-client-id>



postgres:
  auth:
    postgresPassword: <path:value-added-service/data/country-risk/int/postgresql#postgres-password>
    password: <path:value-added-service/data/country-risk/int/postgresql#password>

pgadmin4:
  enabled: false
  secret:
    path: value-added-service/data/country-risk/int/pgadmin4
  ingress:
    hosts:
      - host: vas-pgadmin4.int.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - vas-pgadmin4.int.demo.catena-x.net
        secretName: vas-pgadmin4.int.demo.catena-x.net-tls


