###############################################################
# Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

countryRiskFrontend:

  springProfiles:
    - dev

  appName: vas-country-risk-frontend
  environment: dev

  image:
    registry: "tractusx"
    # -- Name of the docker image
    name: "vas-country-risk"
    pullPolicy: Always
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: "2.0.0-alpha17"

  ingress:
    host: catenax-vas-dev.demo.catena-x.net
    enabled: true

  certificate:
    host: "country-risk-dashboard.dev.demo.catena-x.net"

  configmap:
    # Specifies whether a configmap should be created or not
    data:
      REACT_APP_AUTH_URL: 'https://centralidp.dev.demo.catena-x.net/auth'
      REACT_APP_COUNTRY_RISK_API: 'https://vas-country-risk-backend.dev.demo.catena-x.net'
      REACT_APP_PORTAL_FRONTEND: 'https://portal.dev.demo.catena-x.net'
      REACT_APP_PORTAL_BACKEND: 'https://portal-backend.dev.demo.catena-x.net'
      REACT_APP_COUNTRY_RISK_CLIENT: app9

countryRiskBackend:

  springProfiles:
    - dev

  appName: vas-country-risk-backend
  environment: dev

  image:
    registry: "tractusx"
    # -- Name of the docker image
    name: "vas-country-risk-backend"
    pullPolicy: Always
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: "2.0.0-alpha17"

  ingress:
    enabled: true
    host: catenax-vas-dev.demo.catena-x.net

  certificate:
    host: "vas-country-risk-backend.dev.demo.catena-x.net"

  configmap:
    # Specifies whether a configmap should be created or not
    data:
      spring_profiles_active: dev
      application_host: http://localhost:8080/api/dashboard
      security_enabled: 'true'
      # -- Endpoints for BPDM output gate
      application_bpdm_addressUrl: https://business-partners.dev.demo.catena-x.net/pool/v6/members/addresses/search?
      application_bpdm_siteUrl: https://business-partners.dev.demo.catena-x.net/pool/v6/members/sites/search?
      application_bpdm_legalUrl: https://business-partners.dev.demo.catena-x.net/pool/v6/members/legal-entities/search?
      application_bpdm_genericUrl: https://business-partners.dev.demo.catena-x.net/companies/test-company/v6/output/business-partners/search?
      application_bpdm_consumerManagementUrl: http://localhost:8080/consumerManagementUrl?
      application_bpdm_gateProviderProtocolUrl: http://localhost:8080/gateProviderProtocolUrl?
      application_bpdm_gateProviderId: BPNL0000000XXX
      application_bpdm_policyBpn: BPNL0000000XXX
      application_edc_enabled: 'false'
      vas_auth_url: https://centralidp.dev.demo.catena-x.net

  applicationSecret:
    clientSecret: <path:value-added-service/data/country-risk/dev/keycloak#country-risk-gate-client-secret>
    clientId: <path:value-added-service/data/country-risk/dev/keycloak#country-risk-gate-client-id>
    gateClientSecret: <path:value-added-service/data/country-risk/dev/keycloak#country-risk-gate-client-secret>
    gateClientId: <path:value-added-service/data/country-risk/dev/keycloak#country-risk-gate-client-id>
    poolClientSecret: <path:value-added-service/data/country-risk/dev/keycloak#country-risk-pool-client-secret>
    poolClientId: <path:value-added-service/data/country-risk/dev/keycloak#country-risk-pool-client-id>
    edcApiKey: <path:value-added-service/data/country-risk/dev/edc#controlplane-auth>

postgres:
  auth:
    postgresPassword: <path:value-added-service/data/country-risk/dev/postgresql#postgres-password>
    password: <path:value-added-service/data/country-risk/dev/postgresql#password>

pgadmin4:
  secret:
    path: value-added-service/data/country-risk/dev/pgadmin4
  ingress:
    hosts:
      - host: vas-pgadmin4.dev.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - vas-pgadmin4.dev.demo.catena-x.net
        secretName: vas-pgadmin4.dev.demo.catena-x.net-tls
