springProfiles:
  - int


appName: vas-country-risk-frontend
environment: int

image:
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"
  
ingress:
  host: catenax-vas-int.demo.catena-x.net
  enabled: true

certificate:
  host: "country-risk-frontend.int.demo.catena-x.net"


