# Default values for vas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "ghcr.io"
  name: "catenax-ng/tx-vas-country-risk-frontend"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

certificate:
  host: "localhost"

appName: vas-country-risk-frontend


imagePullSecrets: [ ]

podAnnotations: { }

podSecurityContext:
  fsGroup: 2000

#Spring profiles under which the application should run
springProfiles:
  - dev

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 3000
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080


autoscaling:
  enabled: false

ingress:
  className: nginx
  enabled: false



# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
resources:
  limits:
    cpu: 800m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 1Gi



nodeSelector: { }

tolerations: [ ]

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: DoesNotExist
          topologyKey: kubernetes.io/hostname

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L210
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 1000
  successThreshold: 1
  timeoutSeconds: 1000
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 1000
  successThreshold: 1
  timeoutSeconds: 1000

applicationSecret:
  enabled: false

configmap:
  # Specifies whether a configmap should be created
  create: true


elastic:
  enabled: false
  security:
    tls:
      restEncryption: false

