txdc:
  iatp:
    # Decentralized IDentifier
    id: "did:web:changeme"
    sts:
      dim:
        url: "https://somewhere.dim.org"
      oauth:
        token_url: "https://changeme.org"
        client:
          id: "test-client-id"
          secret_alias: "test-alias"
  controlplane:
    # the ssi object is still needed for the upgradeability test
    # todo: remove this after 0.7.0 is released
    ssi:
      miw:
        url: "http://localhost:8080"
        authorityId: "authorityId"
      oauth:
        client:
          secretAlias: "client-secret"

