postgres:
  enabled: true
  auth:
    password: &psqlPassword "psql_password"
    username: &psqlUsername "postgresql_sandbox_user"
    database: edc
  persistence:
    enabled: true

txdc:
  postgresql:
    enabled: true
    jdbcUrl: "jdbc:postgresql://edc-country-risk-postgres:5432/edc"
    fullnameOverride: "edc-country-risk-postgres"
    username: user
    password: password

  iatp:
    # Decentralized IDentifier
    id: "did:web:changeme"
    sts:
      dim:
        url: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      oauth:
        token_url: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
        client:
          id: "sa122"
          secret_alias: "country-risk/int/edc-consumer/CLIENT_SECRET"

  dataplane:
    token:
      signer:
        # alias under which the private key is stored in the vault (JWK or PEM format)
        privatekey_alias: country-risk/int/edc-provider/DATA_ENCRYPTION_KEYS_ALIAS