postgres:
  enabled: true
  auth:
    password: &psqlPassword "psql_password"
    username: &psqlUsername "postgresql_sandbox_user"
    database: edc
  persistence:
    enabled: true

txdc:
  postgresql:
    enabled: true
    jdbcUrl: "jdbc:postgresql://edc-country-risk-postgres:5432/edc"
    fullnameOverride: "edc-country-risk-postgres"
    username: user
    password: password
