txdc:
  install:
    daps: false
    postgresql: true
    vault: false

  participant:
    id: "BPNL00000007OR16"

  controlplane:
    internationalDataSpaces:
      id: TXDC-Country-Risk
      description: Tractus-X Eclipse IDS Data Space Connector for Country-Risk
      title: ""
      maintainer: ""
      curator: ""
      catalogId: TXDC-Country-Risk-Catalog
    endpoints:
      # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
      management:
        # -- authentication key, must be attached to each 'X-Api-Key' request header
        authKey: #d<>-x9U-\W9'9mb7<08Ro;t
    ## Ingress declaration to expose the network service.
    ingresses:
      ## Public / Internet facing Ingress
      - enabled: true
        # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
        hostname: "country-risk-edc.int.demo.catena-x.net"
        className: "nginx"
        # -- EDC endpoints exposed by this ingress resource
        endpoints:
          - management
          - control
          - protocol
        # -- TLS [tls class](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) applied to the ingress resource
        tls:
          # -- Enables TLS on the ingress resource
          enabled: true
          # -- If present overwrites the default secret name
          secretName: tls-secret
    url:
      # -- Explicitly declared url for reaching the ids api (e.g. if ingresses not used)
      ids: ""

    ssi:
      miw:
        url: "https://managed-identity-wallets-new.int.demo.catena-x.net"
        authorityId: "BPNL00000003CRHK"
      oauth:
        tokenurl: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
        client:
          id: "sa233"
          secretAlias: wlUfawg0SPe5aZexnZVM2F3IhUgzmaca

  dataplane:
    ## Ingress declaration to expose the network service.
    ingresses:
      ## Public / Internet facing Ingress
      - enabled: true
        # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
        hostname: "country-risk-edc.int.demo.catena-x.net"
        # -- EDC endpoints exposed by this ingress resource
        endpoints:
          - public
        # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
        className: "nginx"
        # -- TLS [tls class](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) applied to the ingress resource
        tls:
          # -- Enables TLS on the ingress resource
          enabled: true
          # -- If present overwrites the default secret name
          secretName: tls-secret
    url:
      # -- Explicitly declared url for reaching the public api (e.g. if ingresses not used)
      public: ""

  postgresql:
    jdbcUrl: "jdbc:postgresql://edc-country-risk-postgres:5432/edc"
    fullnameOverride: "edc-country-risk-postgres"
    username: user
    password: password

  vault:
    hashicorp:
      url: "https://vault.demo.catena-x.net"
      token: s.mnHAD9S20ebvV8GHn3mLZlab
      paths:
        secret: /v1/bpdm
    secretNames:
      transferProxyTokenEncryptionAesKey: dev/edc/gate/DATA_ENCRYPTION_KEYS_ALIAS
      transferProxyTokenSignerPrivateKey: dev/edc/gate/DAPS_PRIVATE_KEY
      transferProxyTokenSignerPublicKey: dev/edc/gate/DAPS_PUBLIC_KEY
      dapsPrivateKey: dev/edc/gate/DAPS_PRIVATE_KEY
      dapsPublicKey: dev/edc/gate/DAPS_PUBLIC_KEY

  backendService:
    httpProxyTokenReceiverUrl: "http://edc-country-risk-backend.int.demo.catena-x.net"