################################################################################
# Copyright (c) 2022,2023 BMW Group AG
# Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vas.backend.fullname" . }}
  labels:
    {{- include "vas.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.countryRiskBackend.autoscaling.enabled }}
  replicas: {{ .Values.countryRiskBackend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vas.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.countryRiskBackend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vas.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.countryRiskBackend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # @url: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.countryRiskBackend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.countryRiskBackend.securityContext | nindent 12 }}
          image: {{ .Values.countryRiskBackend.image.registry }}/{{ .Values.countryRiskBackend.image.name }}:{{ default .Chart.AppVersion .Values.countryRiskBackend.image.tag }}
          imagePullPolicy: {{ .Values.countryRiskBackend.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: config-backend
          env:
            - name: VAS_DATASOURCE_HOST
              value: {{ include "vas.postgres.name" . }}
            - name: VAS_DATASOURCE_USER
              value: {{ .Values.postgres.auth.username }}
            - name: VAS_DATASOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name:  {{ include "vas.postgres.name" . }}
                  key: password
            - name: VAS_KEYCLOAK_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: {{ include "vas.applicationSecret.name" . }}
                  key: keycloakClientId
            - name: VAS_KEYCLOAK_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "vas.applicationSecret.name" . }}
                  key: keycloakClientSecret
            - name: VAS_GATECLIENT_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: {{ include "vas.applicationSecret.name" . }}
                  key: gateKeycloakClientId
            - name: VAS_GATECLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "vas.applicationSecret.name" . }}
                  key: gateKeycloakClientSecret
            - name: VAS_POOLCLIENT_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: {{ include "vas.applicationSecret.name" . }}
                  key: poolKeycloakClientId
            - name: VAS_POOLCLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "vas.applicationSecret.name" . }}
                  key: poolKeycloakClientSecret
            - name: APPLICATION_BPDM_APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "vas.applicationSecret.name" . }}
                  key: edcApiKey
          ports:
            - name: http
              containerPort: {{ .Values.countryRiskBackend.service.port }}
              protocol: TCP
          # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes
          livenessProbe:
            httpGet:
              path: {{ .Values.countryRiskBackend.livenessProbe.path }}
              port: {{ .Values.countryRiskBackend.livenessProbe.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.countryRiskBackend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.countryRiskBackend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.countryRiskBackend.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.countryRiskBackend.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.countryRiskBackend.livenessProbe.failureThreshold }}
          # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes
          readinessProbe:
            httpGet:
              path: {{ .Values.countryRiskBackend.readinessProbe.path }}
              port: {{ .Values.countryRiskBackend.readinessProbe.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.countryRiskBackend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.countryRiskBackend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.countryRiskBackend.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.countryRiskBackend.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.countryRiskBackend.readinessProbe.failureThreshold }}

          resources:
            {{- toYaml .Values.countryRiskBackend.resources | nindent 12 }}
          volumeMounts:
            - name: config-backend-volume
              readOnly: true
              mountPath: "/usr/share/nginx/html/config.json"
              subPath: "config.json"
      volumes:
        - name: config-backend-volume
          configMap:
            name: config-backend-negotiation
      {{- with .Values.countryRiskBackend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.countryRiskBackend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.countryRiskBackend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}