name: Country Risk Lint and Test Chart

on:
  push:
    paths:
      - 'charts/country-risk/**'
    branches:
      - main
      - dev
      - fix/**
  pull_request:
    paths:
      - 'charts/country-risk/**'
  workflow_dispatch:
  # Trigger manually
  workflow_call: # Trigger by another workflow
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        default: 'kindest/node:v1.27.3'
        required: false
        type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        with:
          # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
          version: v0.20.0
          # default value for event_name != workflow_dispatch
          node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kind-registry:5000/app-dashboard:testing

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }}
      - name: Run chart-testing (install)
        run: ct install --charts charts/country-risk,charts/country-risk/charts/country-risk-backend,charts/country-risk/charts/country-risk-frontend
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'

        # Upgrade the released chart version with the locally available chart
        # default value for event_name != workflow_dispatch
      - name: Run helm upgrade
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
          helm install country-risk tractusx-dev/charts/country-risk --version ${{ github.event.inputs.upgrade_from || 'x.x.x' }}
          helm dependency update charts/country-risk
          helm upgrade country-risk charts/country-risk
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'